version: '2'

services:
  TradingView:
    image: 'tv:1.0'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TradingView
    depends_on:
      - db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/trading_view
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=teamcoolmjs
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080-8082"

  db:
    image: 'mysql:8.0.29-oracle'
    container_name: db
    environment:
      MYSQL_DATABASE: trading_view
      MYSQL_ROOT_PASSWORD: teamcoolmjs
    ports:
      - "3306:3306"
